name: Update README Links

on:
  push:
    tags:
      - "v*"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Get version and branch
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          BRANCH=$(git branch -r --contains $VERSION | grep -v HEAD | sed 's/origin\///' | head -n 1)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT

      - name: Update README links
        run: |
          # Replace ${VERSION} placeholders with actual version
          sed -i "s|\${VERSION}|${{ steps.get_version.outputs.version }}|g" README.md

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          # Only commit if there are changes
          if [[ -n "$(git status --porcelain)" ]]; then
            git add README.md
            git commit -m "docs: update README links to version ${{ steps.get_version.outputs.version }}"
            git push origin HEAD:${{ steps.get_version.outputs.branch }}
            git tag -f ${{ steps.get_version.outputs.version }}
            git push -f origin ${{ steps.get_version.outputs.version }}
          fi
