name: Update README Links

on:
  push:
    tags:
      - "v*"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version and branch
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Update README links
        run: |
          sed -i "s|\${VERSION}|${{ steps.get_version.outputs.version }}|g" README.md

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git fetch --all --prune
          BRANCH=$(git branch -r --contains ${GITHUB_SHA} | sed 's|origin/||g' | grep -v HEAD | head -n1)

          # If we can’t determine the branch, fail the workflow
          if [ -z "$BRANCH" ]; then
            echo "Error: Could not determine the branch containing commit ${GITHUB_SHA}"
            exit 1
          fi

          git checkout $BRANCH

          if [[ -n "$(git status --porcelain)" ]]; then
            git add README.md
            git commit -m "docs: update README links to version ${{ steps.get_version.outputs.version }}"
            git push origin HEAD:$BRANCH
          fi
